- hosts: localhost
  tasks:
  - name: Download terraform cli
    ansible.builtin.get_url:
      url: https://releases.hashicorp.com/terraform/1.6.1/terraform_1.6.1_linux_amd64.zip
      dest: /tmp/terraform.zip
      mode: '0666' 

   - name: Extract terraform.zip into /tmp/terraform_cli
     ansible.builtin.unarchive:
       src: /tmp/terraform.zip
       dest: /tmp/terraform_cli

   - shell: /tmp/terraform_cli/terraform
